# Generated by Django 5.0.2 on 2024-08-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
